### ISSUE TITLE
Ldb is gpl license .

### ISSUE THREAD

**Issue by tscmga** [LRMPUT/FastABLE#1]
how about other bsd  algorithm ,like gist

**Comment by MichalNowicki** [comment]
Hi,
I proposed the BSD as used it is used in openABLE (https://github.com/roberto-arroyo/OpenABLE) but now I verified that the LDB is really GPL. Therefore, we believe that the license for FastABLE (and also OpenABLE) should be GPL. Please excuse our mistake. I will correct it in a second.

**Comment by tscmga** [comment]
no ！ i hate gpl。
